import LicrasOne from "./source/ropa/mujeres/licrasOne.avif"
import Zapatos from "./source/zapatos/hombres/zapatos_h.avif"
import Botas from "./source/zapatos/mujeres/botasOne_black.jpg"
import Chancletas_Motions_1 from "./source/zapatos/hombres/Chancletas_Motion_Negras.jpeg"
import Chancletas_Motions_2 from "./source/zapatos/hombres/Chancletas_Motion_Carmelita.jpeg"
import Chancletas_Motions_3 from "./source/zapatos/hombres/Chancletas_Motion_Grises.jpeg"
import WhiteAndBlack from "./source/zapatos/hombres/Jordan_Copy_1/Jordan_Copy1_whiteAndblack.avif"
import Blue from "./source/zapatos/hombres/Jordan_Copy_1/Jordan_Copy1_blue.avif"
import Red from "./source/zapatos/hombres/Jordan_Copy_1/Jordan_Copy1_red.avif"
import BlackAndRed3 from "./source/zapatos/hombres/Jordan_Copy_3/Jordan_Copy3_blackAndred_1.avif"
import BlackAndRed3_1 from "./source/zapatos/hombres/Jordan_Copy_3/Jordan_Copy3_blackAndred_2.avif"
import WhiteAndBlack3_2 from "./source/zapatos/hombres/Jordan_Copy_3/Jordan_Copy3_whiteAndblack.avif"
import Sport_Blue from "./source/accesorios/hombres/Guantillas_Deportivas/Sport/sport_blue.avif"
import Sport_Green from "./source/accesorios/hombres/Guantillas_Deportivas/Sport/sport_green.avif"
import Sport_Red from "./source/accesorios/hombres/Guantillas_Deportivas/Sport/sport_red.avif"
import Sport_White from "./source/accesorios/hombres/Guantillas_Deportivas/Sport/sport_white.avif"
import Outdoor_Black from "./source/accesorios/hombres/Guantillas_Deportivas/outdoor/outdoor_black.avif"
import Sirena_Blue from "./source/joyeria/Collar_Sirena/sirena_blue.avif"
import Sirena_Blue1 from "./source/joyeria/Collar_Sirena/sirena_blue_1.avif"
import Sirena_Blue2 from "./source/joyeria/Collar_Sirena/sirena_blue_2.avif"
import Sirena_Pink from "./source/joyeria/Collar_Sirena/sirena_pink.avif"
import Sirena_Purple from "./source/joyeria/Collar_Sirena/sirena_purple.avif"
import Sirena_Red from "./source/joyeria/Collar_Sirena/sirena_red.avif"
import Sirena_Red1 from "./source/joyeria/Collar_Sirena/sirena_red_1.avif"
import Sirena_White from "./source/joyeria/Collar_Sirena/sirena_white.avif"
import Sirena_Yellow from "./source/joyeria/Collar_Sirena/sirena_yellow.avif"
import WomanGafas_Brown from "./source/accesorios/mujeres/womanGafas_brown.avif"
import WomanGafas_Pink from "./source/accesorios/mujeres/womanGafas_pink.avif"
import WomanGafas_Purple from "./source/accesorios/mujeres/womanGafas_purple.avif"
import WomanGafas_Purple1 from "./source/accesorios/mujeres/womanGafas_darkPurple.avif"
import Delta2_Black from "./source/equipos/EcoFlow/Delta2/delta2_black.avif"
import Delta2_Black1 from "./source/equipos/EcoFlow/Delta2/delta2_black_1.avif"
import Delta3_Black from "./source/equipos/EcoFlow/Delta3/delta3_black.avif"




const productsT = [
  { id: 1, 
    type: "Ropa",
    name: "Short",
    category: "Short",
    color: ["red", "green", "blue"],
    brand: "Nike",
    size: ["S", "L", "XL"],
    length: "Corto",
    store: "Temu",
    likes: 0,
    price: 45000, 
    originalPrice: 60000, 
    total_Items: 10,
    description: "Short. Muy uzado en el tiempo de verano",
    genero: ["Mujeres", "Hombres"],
    age: 35,
    rating: 4.5, 
    reviews: 120, 
    img: [LicrasOne],
    status: "new",
    date: "01/04/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  { id: 2, 
    type: "Zapatos",
    name: "Sneakers",
    category: "Zapatillas",
    color: ["red", "green", "blue", "white"],
    brand: "Addidas",
    size: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    length: "",
    store: "Zhein",
    likes: 0,
    price: 25000, 
    originalPrice: 45000, 
    total_Items: 5,
    description: "Zapatillas. Muy uzado en el tiempo de verano",
    genero: ["Mujeres", "Hombres"],
    age: 25,
    rating: 4.7, 
    reviews: 10, 
    img: [Zapatos],
    status: "normal",
    date: "15/02/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  { id: 3, 
    type: "Zapatos",
    name: "Botas",
    category: "Botas",
    color: ["red", "green", "blue", "white"],
    brand: "Addidas",
    size: [35, 37, 38, 39, 40,  42, 43, 45],
    length: "",
    store: "Temu",
    likes: 0,
    price: 45000, 
    originalPrice: 45000, 
    total_Items: 2,
    description: "Botas. Muy uzado en el tiempo de verano",
    genero: ["Mujeres"],
    age: 40,
    rating: 4.0, 
    reviews: 100, 
    img: [Botas],
    status: "old",
    date: "25/12/2025",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  { id: 4, 
    type: "Zapatos",
    name: "Sandalias",
    category: "Sandalias",
    color: ["black", "bagde", "gray"],
    brand: "Motion",
    size: [35, 37, 38, 39, 40,  42, 43, 45],
    length: "",
    store: "Temu",
    likes: 0,
    price: 60000, 
    originalPrice: 80000, 
    total_Items: 2,
    description: "Sandalias. Muy uzado en el tiempo de verano",
    genero: ["Mujeres", "Hombres"],
    age: 40,
    rating: 4.0, 
    reviews: 100, 
    img: [Chancletas_Motions_1, Chancletas_Motions_2, Chancletas_Motions_3],
    status: "new",
    date: "08/04/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {id: 5, 
    type: "Zapatos",
    name: "Tacones",
    category: "Tacones",
    color: ["rojo", "verde", "azul", "blanco", "amarillo"],
    brand: "Addidas",
    size: [35, 37, 42],
    length: "",
    store: "Zhein",
    likes: 0,
    price: 55000, 
    originalPrice: 55000, 
    total_Items: 2,
    description: "Tacones. Muy uzado en el tiempo de verano",
    genero: ["Mujeres"],
    age: 40,
    rating: 2.0, 
    reviews: 0, 
    img: ["https://picsum.photos/300?dress"],
    status: "normal",
    date: "15/03/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {id: 6, 
    type: "Zapatos",
    name: "Chancletas",
    category: "Chancletas",
    color: ["rojo", "blanco", "amarillo"],
    brand: "Addidas",
    size: [35, 37, 42],
    length: "",
    store: "Zhein",
    likes: 0,
    price: 15000, 
    originalPrice: 15000, 
    total_Items: 12,
    description: "Chancletas. Muy uzado en el tiempo de verano",
    genero: ["Mujeres", "Hombres"],
    age: 40,
    rating: 2.0, 
    reviews: 0, 
    img: ["https://picsum.photos/300?dress"],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {id: 7, 
    type: "Ropa",
    name: "Vestido de Verano",
    category: "Vestido",
    color: ["rojo", "verde", "azul"],
    brand: "Nike",
    size: ["XS", "M",  "L", "XL", "XXL"],
    length: "Corto",
    store: "Temu",
    likes: 0,
    price: 45500, 
    originalPrice: 46000, 
    total_Items: 4,
    description: "Vestido Corto. Muy uzado en el tiempo de verano",
    genero: ["Mujeres"],
    age: 15,
    rating: 4.5, 
    reviews: 120, 
    img: ["https://picsum.photos/300?dress"],
    status: "new",
    date: "01/04/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
   {id: 8, 
    type: "Ropa",
    name: "Pantalones",
    category: "Pantalones",
    color: ["rojo", "verde", "azul"],
    brand: "Nike",
    size: ["XS", "M",  "L", "XL", "XXL"],
    length: "",
    store: "Temu",
    likes: 0,
    price: 30000, 
    originalPrice: 30000, 
    total_Items: 10,
    description: "Pantalones. Muy uzado en el tiempo de verano",
    genero: ["Mujeres", "Hombres"],
    age: 30,
    rating: 4.5, 
    reviews: 220, 
    img: ["https://picsum.photos/300?dress"],
    status: "normal",
    date: "11/04/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {id: 9, 
    type: "Ropa",
    name: "Pantalonetas",
    category: "Pantaloneta",
    color: ["rojo", "verde", "azul"],
    brand: "Nike",
    size: ["XS", "M",  "L", "XL", "XXL"],
    length: "",
    store: "Temu",
    likes: 0,
    price: 27000, 
    originalPrice: 33000, 
    total_Items: 20,
    description: "Pantaloneta. Muy uzado en el tiempo de verano",
    genero: ["Mujeres"],
    age: 30,
    rating: 3.5, 
    reviews: 220, 
    img: ["https://picsum.photos/300?dress"],
    status: "normal",
    date: "11/03/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
   {id: 10, 
    type: "Ropa",
    name: "Jeans",
    category: "Jean",
    color: ["rojo", "azul", "negro"],
    brand: "Nike",
    size: ["XS", "M",  "L", "XL"],
    length: "",
    store: "Zhein",
    likes: 0,
    price: 37000, 
    originalPrice: 37000, 
    total_Items: 20,
    description: "Jean. Muy uzado en el tiempo de verano",
    genero: ["Mujeres", "Hombres"],
    age: 30,
    rating: 4.9, 
    reviews: 220, 
    img: ["https://picsum.photos/300?dress"],
    status: "new",
    date: "09/04/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
   {id: 11, 
    type: "Joyeria",
    name: "Anillos",
    category: "Anillos",
    color: ["rojo", "azul", "negro"],
    brand: "Nike",
    size: [6, 7, 8, 9, 10, 11, 12],
    length: "",
    store: "Zhein",
    likes: 0,
    price: 7000, 
    originalPrice: 7000, 
    total_Items: 30,
    description: "Anillos. Muy uzado en el tiempo de verano",
    genero: ["Mujeres", "Hombres"],
    age: 30,
    rating: 4.2, 
    reviews: 220, 
    img: ["https://picsum.photos/300?dress"],
    status: "new",
    date: "09/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 12,
    type: "Joyeria",
    name: "Collares",
    category: "Collares",
    color: ["dorado", "plata", "negro"],
    brand: "Zara",
    size: [],
    length: "45cm",
    store: "Shein",
    likes: 10,
    price: 4500,
    originalPrice: 5000,
    total_Items: 20,
    description: "Collares elegantes ideales para cualquier ocasión",
    genero: ["Mujeres"],
    age: 25,
    rating: 4.5,
    reviews: 150,
    img: ["https://picsum.photos/300?necklace"],
    status: "sale",
    date: "08/04/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 13,
    type: "Ropa",
    name: "Camisetas",
    category: "Tops",
    color: ["blanco", "negro", "verde"],
    brand: "Adidas",
    size: ["S", "M", "L", "XL"],
    length: "",
    store: "Amazon",
    likes: 25,
    price: 2500,
    originalPrice: 3000,
    total_Items: 50,
    description: "Camisetas cómodas para uso diario",
    genero: ["Hombres", "Mujeres"],
    age: 18,
    rating: 4.3,
    reviews: 340,
    img: ["https://picsum.photos/300?shirt"],
    status: "new",
    date: "07/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 14,
    type: "Calzado",
    name: "Zapatillas",
    category: "Sneakers",
    color: ["negro", "gris", "blanco"],
    brand: "Nike",
    size: [7, 8, 9, 10, 11],
    length: "",
    store: "FootLocker",
    likes: 60,
    price: 9000,
    originalPrice: 11000,
    total_Items: 40,
    description: "Zapatillas deportivas de alto rendimiento",
    genero: ["Hombres"],
    age: 20,
    rating: 4.7,
    reviews: 500,
    img: ["https://picsum.photos/300?sneakers"],
    status: "popular",
    date: "06/04/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 15,
    type: "Accesorios",
    name: "Relojes",
    category: "Relojes",
    color: ["negro", "dorado"],
    brand: "Casio",
    size: [],
    length: "",
    store: "eBay",
    likes: 35,
    price: 8000,
    originalPrice: 8500,
    total_Items: 15,
    description: "Relojes modernos con estilo clásico",
    genero: ["Hombres", "Mujeres"],
    age: 28,
    rating: 4.4,
    reviews: 180,
    img: ["https://picsum.photos/300?watch"],
    status: "new",
    date: "05/04/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 16,
    type: "Joyeria",
    name: "Pulseras",
    category: "Pulseras",
    color: ["azul", "rojo", "negro"],
    brand: "Pandora",
    size: ["S", "M", "L"],
    length: "20cm",
    store: "AliExpress",
    likes: 45,
    price: 3000,
    originalPrice: 3500,
    total_Items: 60,
    description: "Pulseras casuales para uso diario",
    genero: ["Mujeres"],
    age: 22,
    rating: 4.6,
    reviews: 270,
    img: ["https://picsum.photos/300?bracelet"],
    status: "sale",
    date: "04/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
{
    id: 17,
    type: "Bolsos",
    name: "Bolso de Mano",
    category: "bolsos",
    color: ["negro", "marron"],
    brand: "Zara",
    size: [],
    length: "",
    store: "Amazon",
    likes: 15,
    price: 6500,
    originalPrice: 7000,
    total_Items: 20,
    description: "Bolso elegante para uso diario",
    genero: ["Mujeres"],
    age: 25,
    rating: 4.3,
    reviews: 120,
    img: ["https://picsum.photos/300?bag"],
    status: "new",
    date: "09/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 18,
    type: "Bolsos",
    name: "Mochila Urbana",
    category: "bolsos",
    color: ["gris", "negro"],
    brand: "Nike",
    size: [],
    length: "",
    store: "Shein",
    likes: 22,
    price: 5000,
    originalPrice: 5500,
    total_Items: 30,
    description: "Mochila moderna para ciudad",
    genero: ["Hombres", "Mujeres"],
    age: 20,
    rating: 4.5,
    reviews: 200,
    img: ["https://picsum.photos/300?backpack"],
    status: "popular",
    date: "08/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 19,
    type: "Bolsos",
    name: "Bolso Deportivo",
    category: "bolsos",
    color: ["azul", "negro"],
    brand: "Adidas",
    size: [],
    length: "",
    store: "eBay",
    likes: 18,
    price: 4800,
    originalPrice: 5200,
    total_Items: 25,
    description: "Ideal para gimnasio",
    genero: ["Hombres"],
    age: 22,
    rating: 4.2,
    reviews: 90,
    img: ["https://picsum.photos/300?gymbag"],
    status: "sale",
    date: "07/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 20,
    type: "Bolsos",
    name: "Bolso Cruzado",
    category: "bolsos",
    color: ["rojo", "negro"],
    brand: "Guess",
    size: ["L"],
    length: "",
    store: "AliExpress",
    likes: 30,
    price: 7200,
    originalPrice: 8000,
    total_Items: 15,
    description: "Bolso compacto y elegante",
    genero: ["Mujeres"],
    age: 27,
    rating: 4.6,
    reviews: 210,
    img: ["https://picsum.photos/300?crossbag"],
    status: "new",
    date: "06/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 21,
    type: "Bolsos",
    name: "Bolso Playero",
    category: "bolsos",
    color: ["beige", "blanco"],
    brand: "H&M",
    size: [],
    length: "",
    store: "Amazon",
    likes: 12,
    price: 3000,
    originalPrice: 3500,
    total_Items: 40,
    description: "Perfecto para verano",
    genero: ["Mujeres"],
    age: 23,
    rating: 4.1,
    reviews: 70,
    img: ["https://picsum.photos/300?beachbag"],
    status: "sale",
    date: "05/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 22,
    type: "Accesorios",
    name: "Gafas de Sol",
    category: "accesorios",
    color: ["negro", "dorado"],
    brand: "RayBan",
    size: [],
    length: "",
    store: "Amazon",
    likes: 50,
    price: 9000,
    originalPrice: 10000,
    total_Items: 25,
    description: "Protección UV con estilo",
    genero: ["Hombres", "Mujeres"],
    age: 30,
    rating: 4.7,
    reviews: 400,
    img: ["https://picsum.photos/300?sunglasses"],
    status: "popular",
    date: "09/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 23,
    type: "Accesorios",
    name: "Cinturón",
    category: "accesorios",
    color: ["marron", "negro"],
    brand: "Levis",
    size: ["S", "M", "L"],
    length: "",
    store: "eBay",
    likes: 20,
    price: 3500,
    originalPrice: 4000,
    total_Items: 30,
    description: "Cinturón clásico",
    genero: ["Hombres"],
    age: 28,
    rating: 4.2,
    reviews: 110,
    img: ["https://picsum.photos/300?belt"],
    status: "new",
    date: "08/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 24,
    type: "Accesorios",
    name: "Sombrero",
    category: "accesorios",
    color: ["negro", "blanco"],
    brand: "NewEra",
    size: [],
    length: "",
    store: "Shein",
    likes: 18,
    price: 2500,
    originalPrice: 3000,
    total_Items: 50,
    description: "Sombrero casual",
    genero: ["Hombres", "Mujeres"],
    age: 21,
    rating: 4.3,
    reviews: 90,
    img: ["https://picsum.photos/300?hat"],
    status: "sale",
    date: "07/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 25,
    type: "Accesorios",
    name: "Bufanda",
    category: "accesorios",
    color: ["gris", "rojo"],
    brand: "Zara",
    size: [],
    length: "",
    store: "Amazon",
    likes: 14,
    price: 2800,
    originalPrice: 3200,
    total_Items: 35,
    description: "Bufanda para invierno",
    genero: ["Mujeres"],
    age: 26,
    rating: 4.1,
    reviews: 60,
    img: ["https://picsum.photos/300?scarf"],
    status: "new",
    date: "06/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 26,
    type: "Accesorios",
    name: "Guantes",
    category: "accesorios",
    color: ["negro"],
    brand: "Nike",
    size: ["M", "L"],
    length: "",
    store: "AliExpress",
    likes: 10,
    price: 2000,
    originalPrice: 2500,
    total_Items: 40,
    description: "Guantes deportivos",
    genero: ["Hombres"],
    age: 24,
    rating: 4.0,
    reviews: 55,
    img: ["https://picsum.photos/300?gloves"],
    status: "sale",
    date: "05/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
  {
    id: 27,
    type: "Maquillaje",
    name: "Base Líquida",
    category: "maquillaje",
    color: ["beige"],
    brand: "Maybelline",
    size: [],
    length: "",
    store: "Amazon",
    likes: 80,
    price: 3000,
    originalPrice: 3500,
    total_Items: 60,
    description: "Cobertura completa",
    genero: ["Mujeres"],
    age: 22,
    rating: 4.6,
    reviews: 500,
    img: ["https://picsum.photos/300?makeup"],
    status: "popular",
    date: "09/04/2026",
     qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
   {id: 28, 
    type: "Zapatos",
    name: "Zapatillas de Baloncesto",
    category: "Zapatillas",
    color: ["red_rojo", "white_blanco", "blue_azul"],
    brand: "Jordan",
    size: [41, 42],
    length: "",
    store: "Temu",
    likes: 0,
    price: 18000, 
    originalPrice: 18000, 
    total_Items: 3,
    description: "Zapatillas de baloncesto de caña alta para hombre — Robustas y estables, zapatillas de entrenamiento unisex con cordones, textura en el arco y suela especializada — Ideales para correr, fitness, baloncesto y caminar — Zapatillas de primavera/verano — El regalo perfecto para hombres — Ligeras, transpirables y ergonómicas.",
    genero: ["Hombres"],
    age: 40,
    rating: 2.0, 
    reviews: 0, 
    img: [WhiteAndBlack, Blue, Red],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },

 ];


const products = [
    {id: 28, 
    type: "Zapatos",
    name: "Zapatillas de Baloncesto",
    category: "Zapatillas",
    color: ["red_rojo", "white_blanco", "blue_azul"],
    brand: "Jordan",
    size: [41, 42],
    length: "",
    store: "Temu",
    likes: 0,
    price: 18000, 
    originalPrice: 18000, 
    total_Items: 3,
    description: `Zapatillas de baloncesto de caña alta para hombre — Robustas  
    y estables, zapatillas de entrenamiento unisex con cordones, textura en el 
    arco y suela especializada — Ideales para correr, fitness, baloncesto y 
    caminar — Zapatillas de primavera/verano — El regalo perfecto para 
    hombres — Ligeras, transpirables y ergonómicas.`,
    genero: ["Hombres"],
    age: 40,
    rating: 2.0, 
    reviews: 0, 
    img: [WhiteAndBlack, Blue, Red],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.temu.com/women-s-autumn-winter-snow-leopard-and-red--printed-wide-leg-pants-fashion-casual--trendy-versatile-drawstring-design-elastic-waist-comfortable--stylish-modern--for-daily-wear-outing-travel-g-605604294794053.html?top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2F33dc1cfc-ce56-4c9b-83fe-6dfa1442ef53.jpg&spec_id=21263&spec_gallery_id=263533&refer_page_sn=10009&freesia_scene=2&_oak_freesia_scene=2&_oak_rec_ext_1=MTM3NQ&_oak_gallery_order=262545729%2C1791130473%2C1927697601%2C953336704%2C1247062918&_oak_mp_inf=EMW29uaz2YkBGiA1MjkzMDI3MWNmNDE0ZTUzOTYyNGU2MGZiOWVmN2U0NiC195Si2TM%3D&spec_ids=21263&search_key=pantalonetas%20de%20mujer%20largas%20anchas&refer_page_el_sn=200049&ab_scene=0&enable_vqr=1&refer_page_name=search_result&refer_page_id=10009_1776309066921_tb4gzy70yq&_x_sessn_id=lvxv466jpz",
  },
    { id: 3, 
    type: "Zapatos",
    name: "Botas",
    category: "Botas",
    color: ["black_negro"],
    brand: "Addidas",
    size: [35, 37, 38],
    length: "",
    store: "Temu",
    likes: 0,
    price: 45000, 
    originalPrice: 45000, 
    total_Items: 4,
    description: `Botas para mujeres — Robustas  
    y estables, zapatillas de entrenamiento unisex con cordones, textura en el 
    arco y suela especializada — Ideales para correr, fitness, baloncesto y 
    caminar — Zapatillas de primavera/verano — El regalo perfecto para 
    hombres — Ligeras, transpirables y ergonómicas.`,
    genero: ["Mujeres"],
    age: 40,
    rating: 4.0, 
    reviews: 100, 
    img: [Botas],
    status: "old",
    date: "25/12/2025",
    qrCode: "https://www.amazon.com/gp/cart/view.html?ref_=nav_cart",
  },
   {id: 35, 
    type: "Zapatos",
    name: "Zapatillas deportivas",
    category: "Zapatillas",
    color: ["black_negro", "white_blanco"],
    brand: "Jordan",
    size: [40, 42],
    length: "",
    store: "Temu",
    likes: 0,
    price: 15000, 
    originalPrice: 15000, 
    total_Items: 2,
    description: `Zapatillas deportivas bajas de moda para hombre 
    con cordones, diseño de rayas y suela plana, ideales para el 
    Festival de Primavera.`,
    genero: ["Hombres"],
    age: 40,
    rating: 3.0, 
    reviews: 0, 
    img: [BlackAndRed3, BlackAndRed3_1, WhiteAndBlack3_2],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.temu.com/women-s-autumn-winter-snow-leopard-and-red--printed-wide-leg-pants-fashion-casual--trendy-versatile-drawstring-design-elastic-waist-comfortable--stylish-modern--for-daily-wear-outing-travel-g-605604294794053.html?top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2F33dc1cfc-ce56-4c9b-83fe-6dfa1442ef53.jpg&spec_id=21263&spec_gallery_id=263533&refer_page_sn=10009&freesia_scene=2&_oak_freesia_scene=2&_oak_rec_ext_1=MTM3NQ&_oak_gallery_order=262545729%2C1791130473%2C1927697601%2C953336704%2C1247062918&_oak_mp_inf=EMW29uaz2YkBGiA1MjkzMDI3MWNmNDE0ZTUzOTYyNGU2MGZiOWVmN2U0NiC195Si2TM%3D&spec_ids=21263&search_key=pantalonetas%20de%20mujer%20largas%20anchas&refer_page_el_sn=200049&ab_scene=0&enable_vqr=1&refer_page_name=search_result&refer_page_id=10009_1776309066921_tb4gzy70yq&_x_sessn_id=lvxv466jpz",
  },
   {id: 36, 
    type: "Accesorios",
    name: "Guantillas Sport",
    category: "Guantillas deportivas",
    color: ["blue_azul", "white_blanco", "green_verde", "red_rojo"],
    brand: "Sport",
    size: ["One Size"],
    length: "",
    store: "Temu",
    likes: 0,
    price: 2500, 
    originalPrice: 2500, 
    total_Items: 4,
    description: `1 par de guantes deportivos multifuncionales 
    de medio dedo para hombre, con almohadillas antideslizantes, 
    ideales para senderismo, gimnasio y deportes.`,
    genero: ["Hombres"],
    age: 40,
    rating: 3.0, 
    reviews: 0, 
    img: [Sport_Blue, Sport_Green, Sport_Red, Sport_White],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.temu.com/women-s-autumn-winter-snow-leopard-and-red--printed-wide-leg-pants-fashion-casual--trendy-versatile-drawstring-design-elastic-waist-comfortable--stylish-modern--for-daily-wear-outing-travel-g-605604294794053.html?top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2F33dc1cfc-ce56-4c9b-83fe-6dfa1442ef53.jpg&spec_id=21263&spec_gallery_id=263533&refer_page_sn=10009&freesia_scene=2&_oak_freesia_scene=2&_oak_rec_ext_1=MTM3NQ&_oak_gallery_order=262545729%2C1791130473%2C1927697601%2C953336704%2C1247062918&_oak_mp_inf=EMW29uaz2YkBGiA1MjkzMDI3MWNmNDE0ZTUzOTYyNGU2MGZiOWVmN2U0NiC195Si2TM%3D&spec_ids=21263&search_key=pantalonetas%20de%20mujer%20largas%20anchas&refer_page_el_sn=200049&ab_scene=0&enable_vqr=1&refer_page_name=search_result&refer_page_id=10009_1776309066921_tb4gzy70yq&_x_sessn_id=lvxv466jpz",
  },
   {id: 46, 
    type: "Accesorios",
    name: "Guantillas Outdoor",
    category: "Guantillas deportivas",
    color: ["black_negro"],
    brand: "Outdoor",
    size: ["One Size"],
    length: "",
    store: "Temu",
    likes: 0,
    price: 2000, 
    originalPrice: 2000, 
    total_Items: 1,
    description: `Un par de guantes deportivos de medio dedo 
    para exteriores: transpirables y duraderos, con múltiples 
    cierres de botones y un diseño texturizado para un ajuste
     perfecto. Aptos tanto para hombres como para mujeres, 
     ideales para actividades al aire libre cotidianas, 
     entrenamientos y como complemento para el fitness.`,
    genero: ["Hombres"],
    age: 40,
    rating: 3.0, 
    reviews: 0, 
    img: [Outdoor_Black],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.temu.com/women-s-autumn-winter-snow-leopard-and-red--printed-wide-leg-pants-fashion-casual--trendy-versatile-drawstring-design-elastic-waist-comfortable--stylish-modern--for-daily-wear-outing-travel-g-605604294794053.html?top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2F33dc1cfc-ce56-4c9b-83fe-6dfa1442ef53.jpg&spec_id=21263&spec_gallery_id=263533&refer_page_sn=10009&freesia_scene=2&_oak_freesia_scene=2&_oak_rec_ext_1=MTM3NQ&_oak_gallery_order=262545729%2C1791130473%2C1927697601%2C953336704%2C1247062918&_oak_mp_inf=EMW29uaz2YkBGiA1MjkzMDI3MWNmNDE0ZTUzOTYyNGU2MGZiOWVmN2U0NiC195Si2TM%3D&spec_ids=21263&search_key=pantalonetas%20de%20mujer%20largas%20anchas&refer_page_el_sn=200049&ab_scene=0&enable_vqr=1&refer_page_name=search_result&refer_page_id=10009_1776309066921_tb4gzy70yq&_x_sessn_id=lvxv466jpz",
  },
   {id: 48, 
    type: "Joyeria",
    name: "Collar de Sirena",
    category: "Aretes",
    color: ["blue_azul", "pink_rosado", "red_rojo", 
      "white_blanco", "yellow_amarillo", "purple_morado"],
    brand: "Mermaid",
    size: ["One Size"],
    length: "",
    store: "Temu",
    likes: 0,
    price: 3000, 
    originalPrice: 3000, 
    total_Items: 6,
    description: `Elegante conjunto de joyería de imitación de 
    sirena con collar y pendientes, ideal para banquetes y bodas. 
    Conjunto de 2 piezas. Regalo perfecto para fiestas y 
    ocasiones especiales.`,
    genero: ["Mujeres"],
    age: 40,
    rating: 3.0, 
    reviews: 0, 
    img: [Sirena_Blue, Sirena_Blue1, Sirena_Blue2, Sirena_Pink, Sirena_Purple, Sirena_Red,
       Sirena_Red1, Sirena_White, Sirena_Yellow],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.temu.com/women-s-autumn-winter-snow-leopard-and-red--printed-wide-leg-pants-fashion-casual--trendy-versatile-drawstring-design-elastic-waist-comfortable--stylish-modern--for-daily-wear-outing-travel-g-605604294794053.html?top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2F33dc1cfc-ce56-4c9b-83fe-6dfa1442ef53.jpg&spec_id=21263&spec_gallery_id=263533&refer_page_sn=10009&freesia_scene=2&_oak_freesia_scene=2&_oak_rec_ext_1=MTM3NQ&_oak_gallery_order=262545729%2C1791130473%2C1927697601%2C953336704%2C1247062918&_oak_mp_inf=EMW29uaz2YkBGiA1MjkzMDI3MWNmNDE0ZTUzOTYyNGU2MGZiOWVmN2U0NiC195Si2TM%3D&spec_ids=21263&search_key=pantalonetas%20de%20mujer%20largas%20anchas&refer_page_el_sn=200049&ab_scene=0&enable_vqr=1&refer_page_name=search_result&refer_page_id=10009_1776309066921_tb4gzy70yq&_x_sessn_id=lvxv466jpz",
  },
     {id: 49, 
    type: "Accesorios",
    name: "Gafas de Sol",
    category: "Gafas",
    color: ["purple_morado","darkPurple_morado oscuro", "brown_marron", "pink_rosado"],
    brand: "Mermaid",
    size: ["One Size"],
    length: "",
    store: "Temu",
    likes: 0,
    price: 3500, 
    originalPrice: 3500, 
    total_Items: 4,
    description: `Gafas Solares`,
    genero: ["Mujeres"],
    age: 40,
    rating: 3.0, 
    reviews: 0, 
    img: [WomanGafas_Brown, WomanGafas_Pink, WomanGafas_Purple, WomanGafas_Purple1],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.temu.com/women-s-autumn-winter-snow-leopard-and-red--printed-wide-leg-pants-fashion-casual--trendy-versatile-drawstring-design-elastic-waist-comfortable--stylish-modern--for-daily-wear-outing-travel-g-605604294794053.html?top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2F33dc1cfc-ce56-4c9b-83fe-6dfa1442ef53.jpg&spec_id=21263&spec_gallery_id=263533&refer_page_sn=10009&freesia_scene=2&_oak_freesia_scene=2&_oak_rec_ext_1=MTM3NQ&_oak_gallery_order=262545729%2C1791130473%2C1927697601%2C953336704%2C1247062918&_oak_mp_inf=EMW29uaz2YkBGiA1MjkzMDI3MWNmNDE0ZTUzOTYyNGU2MGZiOWVmN2U0NiC195Si2TM%3D&spec_ids=21263&search_key=pantalonetas%20de%20mujer%20largas%20anchas&refer_page_el_sn=200049&ab_scene=0&enable_vqr=1&refer_page_name=search_result&refer_page_id=10009_1776309066921_tb4gzy70yq&_x_sessn_id=lvxv466jpz",
  },
     {id: 52, 
    type: "Equipos",
    name: "EcoFlow Delta 2",
    category: "EcoFlow",
    color: ["black_negro"],
    brand: "EcoFlow",
    size: ["16cm/24cm/15cm"],
    length: "",
    store: "Temu",
    likes: 0,
    price: 15000, 
    originalPrice: 15000, 
    total_Items: 1,
    description: `EcoFlow Delta 2`,
    genero: ["Unisex"],
    age: 40,
    rating: 4.2, 
    reviews: 0, 
    img: [Delta2_Black, Delta2_Black1],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.temu.com/women-s-autumn-winter-snow-leopard-and-red--printed-wide-leg-pants-fashion-casual--trendy-versatile-drawstring-design-elastic-waist-comfortable--stylish-modern--for-daily-wear-outing-travel-g-605604294794053.html?top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2F33dc1cfc-ce56-4c9b-83fe-6dfa1442ef53.jpg&spec_id=21263&spec_gallery_id=263533&refer_page_sn=10009&freesia_scene=2&_oak_freesia_scene=2&_oak_rec_ext_1=MTM3NQ&_oak_gallery_order=262545729%2C1791130473%2C1927697601%2C953336704%2C1247062918&_oak_mp_inf=EMW29uaz2YkBGiA1MjkzMDI3MWNmNDE0ZTUzOTYyNGU2MGZiOWVmN2U0NiC195Si2TM%3D&spec_ids=21263&search_key=pantalonetas%20de%20mujer%20largas%20anchas&refer_page_el_sn=200049&ab_scene=0&enable_vqr=1&refer_page_name=search_result&refer_page_id=10009_1776309066921_tb4gzy70yq&_x_sessn_id=lvxv466jpz",
  },
   {id: 5, 
    type: "Equipos",
    name: "EcoFlow Delta 3",
    category: "EcoFlow",
    color: ["black_negro"],
    brand: "EcoFlow",
    size: ["26cm/34cm/25cm"],
    length: "",
    store: "Temu",
    likes: 0,
    price: 375000, 
    originalPrice: 375000, 
    total_Items: 1,
    description: `EcoFlow Delta 3`,
    genero: ["Unisex"],
    age: 40,
    rating: 4.2, 
    reviews: 0, 
    img: [Delta3_Black],
    status: "normal",
    date: "01/01/2026",
    qrCode: "https://www.temu.com/women-s-autumn-winter-snow-leopard-and-red--printed-wide-leg-pants-fashion-casual--trendy-versatile-drawstring-design-elastic-waist-comfortable--stylish-modern--for-daily-wear-outing-travel-g-605604294794053.html?top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2F33dc1cfc-ce56-4c9b-83fe-6dfa1442ef53.jpg&spec_id=21263&spec_gallery_id=263533&refer_page_sn=10009&freesia_scene=2&_oak_freesia_scene=2&_oak_rec_ext_1=MTM3NQ&_oak_gallery_order=262545729%2C1791130473%2C1927697601%2C953336704%2C1247062918&_oak_mp_inf=EMW29uaz2YkBGiA1MjkzMDI3MWNmNDE0ZTUzOTYyNGU2MGZiOWVmN2U0NiC195Si2TM%3D&spec_ids=21263&search_key=pantalonetas%20de%20mujer%20largas%20anchas&refer_page_el_sn=200049&ab_scene=0&enable_vqr=1&refer_page_name=search_result&refer_page_id=10009_1776309066921_tb4gzy70yq&_x_sessn_id=lvxv466jpz",
  },
]

/* Modify the data to add a new key 
(amount of item by color) 
ex: itemByColor: {
  black: 1,
  white: 0,
  red: 0,
  blue: 0,
  green: 0,
  yellow: 0,
  pink: 0,
  purple: 0,
  darkPurple: 0,
  gray: 0,
  brown: 0,
  orange: 0,
  gold: 0,
  silver: 0
}
so when uswer choose a color the application knows how many items got 
left in the store of that color */

const categoryData = [
  {
    name: "Ropa",
    sub: ["Shorts", "Vestidos", "Pantalones", "Jeans", "Pantalonestas",
      "Blusas", "Pulovers", "Vikinis", "Medias de Hombres", "Medias de mujeres",
      "Enterizos"
    ],
    filters: ["Tipo", "Nombre", "Categoria",  "Colores", "Marcas", "Tallas", "Largo",
      "Tienda", "Precio", "Descuento", "Cantidad",  "Rating", "Comentarios", "Sexo", 
      "Edad"
    ],
    personInCharge: "Jonelkis Àvila"
  },
  {
    name: "Zapatos",
    sub: ["Botas", "Sandalias", "Zapatillas", "Tacones", "Chancletas"],
    filters: ["Tallas", "Colores", "Material", "Marcas", "Descuento"],
     personInCharge: "Jonelkis Àvila"
  },
  {
    name: "Joyeria",
    sub: ["Anillos", "Cadenas", "Aretes", "Brazaletes", "Relojes"],
    filters: ["Material", "Colores", "Sexo", "Edad", "Descuento"],
     personInCharge: "Jonelkis Àvila"
  },
  {
    name: "Bolsos",
    sub: ["Bolsos de Mano", "Mochilas", "Maletas de Viaje", 
      "Carteras", "Billeteras", "Loncheras"],
    filters: ["Colores", "Edad", "Material", "Sexo", "Descuento"],
    personInCharge: "Jonelkis Àvila"
  },
  {
    name: "Accesorios",
    sub: ["Cintos", "Gorras", "Gafas", "Cintillos", "Ligas", "Felpas",
      "Pelliscos", "Pasadores", "Pulseras", "Gemelos de camisas", 
      "Sombreros", "Pachangas", "Pamelas", "Guantillas deportivas"
    ],
    filters: ["Colores", "Marcas", "Material", "Sexo", "Descuento"],
    personInCharge: "Jonelkis Àvila"
  },
  {
    name: "Maquillaje",
    sub: ["Gloss", "Base en Polvo", "Creyones" ,
      "Exfoliante Corporal", "Esponjas", "Brochas", 
      "Sombras", "Iluminador", "Basa Liquida", "Deliniadores", "Rimer" ],
    filters: ["Marcas", "Colores", "Descuento"], 
     personInCharge: "Lisandra Ojeda"
  },
  {
    name: "Productos de Pelo",
    sub: ["Shampoo", "Acondicionador", "Aceites", "Keratinas", "Mascarilla", 
        "Tintes", "Peroxido", "Descoloracion"],
    filters: ["Tipo de Pelo", "Marcas", "Colores", 
        "Volumen", "Tratamientos", "Descoloracion tipos", "Descuento"],
     personInCharge: "Lisandra Ojeda"
  },
  {
    name: "Productos de Uñas",
    sub: ["Polvo de Acrilico", "Liquido", "Uñas", "Carcamonias", "Piedras", 
      "Ginceles", "Gel Secado Lentro", "Gel Secado Rapido", "Polvo de Colores", 
      "Pintura de Gel", "Polvo Blanco", "Polvo Rosado", "Acetona", "Lima", 
      "Anti-Hongos", "Bloques de Uñas", "Alicate", "Poli-Gel", "Removedor de Cuticulas",
      "Joyas de las Uñas"],
    filters: ["Numeros", "Marcas", "Tipos", "Descuento"],
    personInCharge: "Lisandra Ojeda"
  },
  { 
    name: "Equipos",
    sub: ["Herramientas de Uñas", "Ventiladores", "Tenazas", 
      "Secadores", "Lavadoras", "Bocinas", "Planchas de Pelo", "EcoFlow", 
      "Refrigeradores", "Neveras", "Oyas Arrozeras", "Oyas Multipropositos",
       "TV", "Cafeteras Electricas", "Cafeteras", "MicroWay", "Cocinas con Hornos", 
      "Linternas"],
      filters: ["Marcas", "Tipos", "Descuento"],
      personInCharge: "Lisandra Ojeda"
  },
  { 
    name: "Electronicos",
    sub: ["Tablet", "Laptop", "Mobiles", "XBoss", "Nintendo", "Play Station", 
      "Audifonos", "Cables", "Extension Electrica"],
    filters: ["Marcas", "Descuento"],
    personInCharge: "Lisandra Ojeda"
  }
];

const colorMap = {
  black: "Negro",
  white: "Blanco",
  red: "Rojo",
  blue: "Azul",
  green: "Verde",
  yellow: "Amarillo",
  pink: "Rosado",
  purple: "Morado",
  darkPurple: "Morado Oscuro",
  gray: "Gris",
  brown: "Marrón",
  orange: "Naranja",
  gold: "Dorado",
  silver: "Plateado"
};

const administrador = [
  {
    name: "Jonelkis Àvila",
    phone: "5356428430",
    address: "Mariana Grajales #810 Reparto La Risueña, Santiago de Cuba, Cuba",
    job: "Administradora / Dependienta"
  },
  {
    name: "Lisandra Ojeda",
    phone: "5350031672",
    address: "Calle 5ta Ducoreaux #62 El Caney, Santiago de Cuba, Cuba",
    job: "Administradora / Dependienta"
  },
  {
    name: "Daniela Paniagua",
    phone: "5358753021",
    address: "Mariana Grajales #810 Reparto La Risueña, Santiago de Cuba, Cuba",
    job: "Gestora de Ventas"
  },
  {
    name: "Gabriela Rocío",
    phone: "5353566340",
    address: "Mariana Grajales #13, entre A y C, Petrocasa, Santiago de Cuba, Cuba",
    job: "Gestora de Ventas"
  },
  {
    name: "Denis Ernesto",
    phone: "5363191892",
    address:  "Mariana Grajales #810 Reparto La Risueña, Santiago de Cuba, Cuba",
    job: "Gestor de Venta"
  },
  {
    name: "Silvia Vilma",
    phone: "5354333471",
    address: "Mariana Grajales #840 Reparto La Risueña, Santiago de Cuba, Cuba",
    job: "Administradora / Contadora"
  },
    {
    name: "Alexander La Rosa",
    phone: "5350332088",
    address: "Mariana Grajales #840 Reparto La Risueña, Santiago de Cuba, Cuba",
    job: "Administrador"
  }
];

const customers = [
  { 
    customerId: 0,
    name: "",
    email: "",
    phone: "",
    imagen: "",
    address: "",
    userCreate: new Date(),
    order: [
      { id: 0,
        qrcode: "",
        admInCharge: "",
        gestorSell: "",
        orders: [],
        dollarPrice: "",
        cupPrice: "",
        revenewTotal: "",
        date: new Date(),
        paymentFormat: ""
      }
    ],
    orderProccess:[
      {
        id: 0,
        qrcode: "",
        admInCharge: "",
        gestorSell: "",
        orders: [],
        dollarPrice: "",
        cupPrice: "",
        revenewTotal: "",
        date: "",
        paymentFormat: "",
        paymentOption:  "",
     }
  ],
    delivered: [
      {
        id: 0,
        qrcode: "",
        admInCharge: "",
        gestorSell: "",
        orders: [],
        dollarPrice: "",
        cupPrice: "",
        revenewTotal: "",
        date: "",
        paymentFormat: "",
        paymentOption:  "",
     },
  ]
  }
]

export default {productsT, categoryData, products, colorMap, administrador};